name: Build Caddy Windows

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest   # ← فقط ویندوز

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build Caddy (Windows)
        run: |
          xcaddy build ^
            --with github.com/caddy-dns/arvancloud ^
            --output caddy.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: caddy-windows
          path: caddy.exe
