name: Build Caddy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build Caddy
        run: |
          xcaddy build \
            --with github.com/caddy-dns/arvancloud

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: caddy
          path: ./caddy
